const DESTINATIONS=['Lisbon','Prague','Budapest','Barcelona','Rome','Vienna','Madrid','Paris','Amsterdam','Athens'];
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const hash=s=>[...String(s)].reduce((a,c)=>((a<<5)-a+c.charCodeAt(0))|0,0);
const placeCache=new Map();
async function getJSON(url){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),6500);try{const r=await fetch(url,{signal:ctl.signal,headers:{'user-agent':'OTATAM-prototype/1.3'}});if(!r.ok)throw new Error(`Грешка от доставчик ${r.status}`);return await r.json()}finally{clearTimeout(timer)}}
async function geocode(name){const d=await getJSON('https://geocoding-api.open-meteo.com/v1/search?name='+encodeURIComponent(name)+'&count=1&language=bg&format=json');if(!d.results?.length)throw new Error('Дестинацията не е намерена');const x=d.results[0];return{name:x.name,country:x.country||'',lat:x.latitude,lon:x.longitude,timezone:x.timezone||'auto'}}
async function weather(lat,lon){const d=await getJSON(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m&timezone=auto`),c=d.current||{};return{temperature:c.temperature_2m??0,feels:c.apparent_temperature??0,code:c.weather_code??0,wind:c.wind_speed_10m??0}}
function irrelevant(title,dest){const t=title.toLowerCase(),d=dest.toLowerCase();return t===d||/^(history of|list of|timeline of|siege of|battle of|district of)/i.test(title)||/\b(\d{4}|\d{3} bc)\b/i.test(title)}
async function wikiPlaces(lat,lon,limit,destName){const key=`${lat.toFixed(3)}:${lon.toFixed(3)}:${limit}`,cached=placeCache.get(key);if(cached&&Date.now()-cached.at<30*60*1000)return cached.data;const params=new URLSearchParams({action:'query',generator:'geosearch',ggscoord:`${lat}|${lon}`,ggsradius:'10000',ggslimit:String(Math.max(30,limit*2)),ggsnamespace:'0',prop:'coordinates|pageimages|pageprops',piprop:'thumbnail',pithumbsize:'1000',format:'json',origin:'*'});const d=await getJSON('https://en.wikipedia.org/w/api.php?'+params.toString()),pages=Object.values(d.query?.pages||{}).sort((a,b)=>(a.index||999)-(b.index||999)),out=[];for(const p of pages){const c=p.coordinates?.[0];if(!c||irrelevant(p.title,destName))continue;out.push({name:p.title,lat:c.lat,lon:c.lon,wikidata:p.pageprops?.wikibase_item||null,wikipedia:`en:${p.title}`,image:p.thumbnail?.source||null,source:'Wikipedia GeoSearch / Wikidata',coordinateConfidence:'координати-на-конкретното-място'});if(out.length>=limit)break}placeCache.set(key,{at:Date.now(),data:out});return out}
function decorate(p,i,input){const photo=(input.interests||[]).includes('photo');return{name:p.name,lat:p.lat,lon:p.lon,category:'Забележителност',duration:60,booking:false,description:'Реално място от Wikipedia/Wikidata с конкретни координати.',why:'Подбрано според избраното темпо и интереси, така че маршрутът да остане практичен.',photoTip:photo?'Подходящо е да се посети сутрин или привечер; провери натовареността преди посещение.':'Провери условията и работното време преди посещение.',hiddenGem:i%4===3,wikidata:p.wikidata,wikipedia:p.wikipedia,image:p.image,website:null,phone:null,openingHours:null,address:null,source:p.source,coordinateConfidence:p.coordinateConfidence}}
function buildDays(places,input,dest){const per=input.pace==='relaxed'?3:input.pace==='fast'?5:4,days=[];for(let d=0;d<input.days;d++){const start=(d*per)%places.length,stops=[];for(let j=0;j<per&&j<places.length;j++)stops.push(decorate(places[(start+j)%places.length],j+d*per,input));days.push({title:d===0?`Първи ден в ${dest.name}`:d===input.days-1?'Последни акценти':`Разглеждане на ${dest.name}`,stops})}return days}
function makeBudget(input){const total=Number(input.budget)||0,ratios=input.style==='comfort'?{'Полети':.27,'Настаняване':.39,'Храна':.17,'Активности':.08,'Транспорт':.05,'Резерв':.04}:input.style==='save'?{'Полети':.25,'Настаняване':.28,'Храна':.18,'Активности':.10,'Транспорт':.07,'Резерв':.12}:{'Полети':.27,'Настаняване':.34,'Храна':.18,'Активности':.10,'Транспорт':.06,'Резерв':.05},categories={};for(const[k,v]of Object.entries(ratios))categories[k]=Math.round(total*v);const buffer=categories['Резерв'];delete categories['Резерв'];return{categories,planned:Object.values(categories).reduce((a,b)=>a+b,0),buffer}}
function weatherText(w){const rainy=[51,53,55,56,57,61,63,65,66,67,80,81,82,95,96,99].includes(w.code);return{summary:`В момента: ${Math.round(w.temperature)}°C, усеща се като ${Math.round(w.feels)}°C, вятър ${Math.round(w.wind)} км/ч.`,switch:rainy?'Заради времето: приоритизирай закрити места и провери външните активности.':'Времето е подходящо за външния план; запази една закрита алтернатива.'}}
module.exports=async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'Разрешен е само POST'});try{const input={...(req.body||{})};input.days=clamp(Number(input.days)||4,1,10);input.travellers=clamp(Number(input.travellers)||2,1,10);input.budget=Math.max(150,Number(input.budget)||1500);input.pace=['relaxed','balanced','fast'].includes(input.pace)?input.pace:'balanced';input.style=['save','value','comfort'].includes(input.style)?input.style:'value';if(!Array.isArray(input.interests))input.interests=['culture','architecture'];const picked=(input.destination||'').trim()||DESTINATIONS[Math.abs(hash(input.interests.join('|')+'|'+input.budget+'|'+input.days))%DESTINATIONS.length],dest=await geocode(picked),needed=clamp(input.days*(input.pace==='relaxed'?3:input.pace==='fast'?5:4),8,24),[w,places]=await Promise.all([weather(dest.lat,dest.lon),wikiPlaces(dest.lat,dest.lon,needed,dest.name)]);if(places.length<4)throw new Error('Няма достатъчно надеждни места за тази дестинация');const days=buildDays(places,input,dest),all=days.flatMap(x=>x.stops),wt=weatherText(w),budget=makeBudget(input);res.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=600');return res.status(200).json({generatedAt:new Date().toISOString(),input,destination:dest,weather:{...w,...wt},days,budget,totalStops:all.length,hiddenGems:all.filter(x=>x.hiddenGem).length,photoSpots:all.filter(x=>x.image).length,confidence:{places:'wikipedia-wikidata-coordinates',weather:'live',budget:'estimated',flights:'check-before-booking',stay:'check-before-booking'},status:'needs_review'})}catch(e){return res.status(500).json({error:e.message||'Генерирането не успя'})}}
